### ISSUE TITLE
.gha files

### ISSUE THREAD

**Issue by bendnorman** [RobotExMachina/Machina-Grasshopper#1]
Hi There!

I am hoping to experiment with Machina-Grasshopper however I can't find any of the main or sample .gha files in the repo.  Where are they?

Thanks,
Ben

**Comment by garciadelcastillo** [comment]
Hi @bendnorman , 

The main distribution .zip file in `/dist` comes with the .gha, .dlls, instructions on how to install and a folder of sample files.  

Go to `https://github.com/garciadelcastillo/Machina-Grasshopper/tree/master/dist`, download and extract the .zip file, and you will find all the goodies ;)

JL
