### ISSUE TITLE
Stream Mode and BufferEmpty Event for GH?

### ISSUE THREAD

**Issue by bendnorman** [RobotExMachina/Machina-Grasshopper#2]
Hi there!

I read in `Machina/Walkthrough.md` about the `BufferEmpty()` event for "Stream" mode.  Does "Stream" mode and `BufferEmpty()` function exist in Machina-Grasshopper? If so, how do I them?

Thanks

**Comment by garciadelcastillo** [comment]
Hi! 

Currently, the GH wrapper doesn't take advantage of any of the real-time features of Machina and is only usable for offline programming. Hopefuly, this will change sometime soon ;)


JL

**Comment by garciadelcastillo** [comment]
Hi @bendnorman 

The new GH release can now listen to events coming from the Bridge ;)
