### ISSUE TITLE
External Axis Movement Through Machina 

### ISSUE THREAD

**Issue by rohansaklecha** [RobotExMachina/Machina-Grasshopper#5]
Hi, I am trying to move an external track on an ABB 6700 using Machina GH in real time with Bridge. The command goes through but the robot does not actually move. All other internal axis movements are working fine in this workflow. I have attached a screenshot of the GH script below. For your reference, I am using a 'State Gate' widget from Fologram plugin in this file.

Do you know the reason why Machina is unable to move the external axis?

![Screenshot (9)](https://user-images.githubusercontent.com/85638048/128208801-0013af2c-ea8e-404f-b59e-a49e26775182.png)

**Comment by garciadelcastillo** [comment]
Hi @rohansaklecha , 

The `ExternalAxis` command doesn't actuate the external axes _right away_, but sets them to be changed synchronously with the _next action_. That means that when you follow the `ExternalAxis` actin with a `MoveTo` action for example, the robot will move to the position specified by `MoveTo` with the external axis specified by `ExternalAxis`. This is the majority of the use cases.

If instead, you want to _move the external axis only_, you can issue a `ExternalAxis` action followed by a "stay in place" action such as the relative `Move(0, 0, 0)`.

Does this make sense? Let me know if you got it :)

**Comment by rohansaklecha** [comment]
Thanks Jose, that was certainly helpful. Now the track movement works!
