### ISSUE TITLE
Custom Code through Machina Bridge

### ISSUE THREAD

**Issue by LoyWeiWin** [RobotExMachina/Machina-Grasshopper#6]
Hey Jose,

Just out of curiosity, if the custom code cmd is still only available for offline programming? If there are any alternative solution to push the custom cmd through machina bridge? Thank you so much for the help =)

**Comment by garciadelcastillo** [comment]
Hi @LoyWeiWin,

Custom code is mostly available only for offline code, and no plans as of right now to extend it to work online :(
